# Form implementation generated from reading ui file 'vote_menu.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(500, 500)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        MainWindow.setMaximumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ID_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.ID_label.setGeometry(QtCore.QRect(20, 130, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.ID_label.setFont(font)
        self.ID_label.setObjectName("ID_label")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(110, 10, 281, 81))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.ID_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ID_input.setGeometry(QtCore.QRect(210, 150, 271, 41))
        self.ID_input.setObjectName("ID_input")
        self.candidate_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.candidate_label.setGeometry(QtCore.QRect(70, 210, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.candidate_label.setFont(font)
        self.candidate_label.setObjectName("candidate_label")
        self.vote_john = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.vote_john.setGeometry(QtCore.QRect(210, 270, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.vote_john.setFont(font)
        self.vote_john.setObjectName("vote_john")
        self.vote_jane = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.vote_jane.setGeometry(QtCore.QRect(210, 310, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.vote_jane.setFont(font)
        self.vote_jane.setObjectName("vote_jane")
        self.vote_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.vote_button.setGeometry(QtCore.QRect(170, 380, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.vote_button.setFont(font)
        self.vote_button.setObjectName("vote_button")
        self.error_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(170, 430, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.error_label.setFont(font)
        self.error_label.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.error_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.error_label.setObjectName("error_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Please cast your vote."))
        self.ID_label.setText(_translate("MainWindow", "ID Number"))
        self.title_label.setText(_translate("MainWindow", "Time to vote!"))
        self.candidate_label.setText(_translate("MainWindow", "Please select your candidate of choice."))
        self.vote_john.setText(_translate("MainWindow", "John"))
        self.vote_jane.setText(_translate("MainWindow", "Jane"))
        self.vote_button.setText(_translate("MainWindow", "CAST VOTE"))
        self.error_label.setText(_translate("MainWindow", "Already voted"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
